### ISSUE TITLE
brick-0.34.1 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [jtdaugherty/brick#162]
~~~
Preprocessing library for brick-0.34.1..
Building library for brick-0.34.1..
[ 1 of 22] Compiling Brick.AttrMap    ( src/Brick/AttrMap.hs, dist/build/Brick/AttrMap.o )

src/Brick/AttrMap.hs:73:10: error:
    • No instance for (Semigroup AttrName)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid AttrName’
   |
73 | instance Monoid AttrName where
   |          ^^^^^^^^^^^^^^^
[ 2 of 22] Compiling Brick.BChan      ( src/Brick/BChan.hs, dist/build/Brick/BChan.o )
[ 3 of 22] Compiling Brick.Types.TH   ( src/Brick/Types/TH.hs, dist/build/Brick/Types/TH.o )
[ 5 of 22] Compiling Brick.Widgets.Border.Style ( src/Brick/Widgets/Border/Style.hs, dist/build/Brick/Widgets/Border/Style.o )
[21 of 22] Compiling Data.Text.Markup ( src/Data/Text/Markup.hs, dist/build/Data/Text/Markup.o )

src/Data/Text/Markup.hs:31:10: error:
    • No instance for (Semigroup (Markup a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Markup a)’
   |
31 | instance Monoid (Markup a) where
   |          ^^^^^^^^^^^^^^^^^
~~~

See https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid for details.

**Comment by JackKiefer** [comment]
Aahh! I tried submitting [herms](github.com/jackkiefer/herms) to Stackage the same day they switched their builds to GHC 8.4.1, and now this is is preventing us from getting added. Some unfortunate timing, haha!

I think I'll try and jump in and fix this.

**Comment by jtdaugherty** [comment]
At the moment `master` is fixed just by bounding the `base` constraint, and I've done the same on the latest couple of Hackage releases. That just turns build failures into constrain solving failures, though. I haven't had time to add the appropriate CPP and code to fix this in general, so if you want to, that would be appreciated!

**Comment by jtdaugherty** [comment]
Thanks - I fixed both of the revisions I changed.

**Comment by jtdaugherty** [comment]
This is now fixed and release in `0.35`. Thanks!

**Comment by simonmichael** [comment]
Hi @jtdaugherty, 
This is causing problems with hledger-ui's homebrew packaging today. They use ghc 8.8 and cabal v1-install, which is picking brick 0.26, which [fails to build](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/55208/version=catalina/testReport/junit/brew-test-bot/catalina/install___build_bottle_hledger/).

What's the right solution here ? Strictly speaking, because of cabal (v1?)'s wild build planning I think *all* those old versions of brick which don't build with modern GHC should have upper bounds applied with a hackage revision. Would this be possible ?

(I'd also like to get homebrew to use a more robust command in CI, but that's a harder problem.)

**Comment by simonmichael** [comment]
PS https://matrix.hackage.haskell.org/#/package/brick shows the versions affected (the red cells, 0.26.1 back to 0.1).

**Comment by jtdaugherty** [comment]
@simonmichael thanks for the report. Your link gives me a 404 response. Can you link to another build with this problem?

I'd really like to know what is causing this, because frankly I don't want to have to go update the metadata for a few dozen versions of the package unless I absolutely have to.

**Comment by simonmichael** [comment]
Sorry I don't have one, I guess homebrew CI expires them. Commands like these should show some build failures:
```
stack --resolver nightly-2020-01-06 build brick-0.26 --fast
cabal install -w /Users/simon/.stack/programs/x86_64-osx/ghc-8.8.1/bin/ghc brick-0.26
```
Output:
```
brick      > Configuring brick-0.26...
brick      > build
brick      > Preprocessing library for brick-0.26..
brick      > Building library for brick-0.26..
brick      > [ 1 of 20] Compiling Brick.AttrMap
brick      > 
brick      > /private/var/folders/r7/f9j9c2zd1k97v47cr84j_qvc0000gn/T/stack24248/brick-0.26/src/Brick/AttrMap.hs:70:10: error:
brick      >     • No instance for (Semigroup AttrName)
brick      >         arising from the superclasses of an instance declaration
brick      >     • In the instance declaration for ‘Monoid AttrName’
brick      >    |
brick      > 70 | instance Monoid AttrName where
brick      >    |          ^^^^^^^^^^^^^^^
brick      > 
brick      > /private/var/folders/r7/f9j9c2zd1k97v47cr84j_qvc0000gn/T/stack24248/brick-0.26/src/Brick/AttrMap.hs:153:15: error:
brick      >     • The constructor ‘Attr’ should have 4 arguments, but has been given 3
brick      >     • In the pattern: Attr s1 f1 b1
brick      >       In an equation for ‘combineAttrs’:
brick      >           combineAttrs (Attr s1 f1 b1) (Attr s2 f2 b2)
brick      >             = Attr
brick      >                 (s1 `combineMDs` s2) (f1 `combineMDs` f2) (b1 `combineMDs` b2)
brick      >     |
brick      > 153 | combineAttrs (Attr s1 f1 b1) (Attr s2 f2 b2) =
brick      >     |               ^^^^^^^^^^^^^
brick      > 
Completed 4 action(s).

--  While building package brick-0.26 using:
      /Users/simon/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.0.0_ghc-8.8.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.0.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by jtdaugherty** [comment]
Thanks! I meant to ask why is 0.26 getting selected, not why it is failing to build.

**Comment by simonmichael** [comment]
cabal can do that any time for its own reasons, unless you explicitly lock down the version of every package. I don’t know why it was doing it this time.

**Comment by jtdaugherty** [comment]
I suggest you consider putting a lower bound on `brick`. In my experience this problem is indicative of a problem in a newer dependency, or in a change in a transitive dependency constraint. In this case, newer version of `brick` could be getting rejected for all sorts of reasons, and putting a lower bound on `brick` in your own package should reveal the true nature of the problem.

Besides, I suspect that you don't actually expect old versions of brick to build with your package. Even relatively recent versions of `brick` introduced top-level breaking API changes that I'm sure you had to contend with, and in that case it would have been important to introduce a brick lower bound anyway.

I realize this may sound like I'm saying this isn't my problem. I see brick metadata changes as another way to help the real problem surface, and I agree that it's confusing if cabal rejects enough new versions of a package to start trying ancient ones. But frankly the amount of work it would take to fix those old versions isn't really work I want to do, and since you maintain an executable package, it's usually a good practice for executable packages to have very tight dependency bounds to prevent exactly this kind of situation.

**Comment by simonmichael** [comment]
@jtdaugherty it does sound like that yes. :) The fact is that you have some published some packages on Hackage with incorrect bounds. They say they are buildable with GHC 8.4+, but they aren't. Though they're old versions none of us cares about, cabal can and will sometimes pick them for its install plan (as this real world example shows).. for its own inscrutable reasons.. because your bounds allow it to.

Putting a lower bound on brick could be a workaround but it's a kludge; it needlessly prevents someone building latest hledger with older brick versions, as might be desirable when someone is using an old GHC. (hledger supports GHC back to 8.0, and until recently 7.10).

The fix I was imagining was that you would apply hackage revisions to fix the upper base bound on each old version - I figured that's tedious but probably quite doable. If it's more hassle than that or just not something you want to do, that's fair and I won't worry about it. I just wanted to make you aware. For me the real solution will be to get away from this cabal behaviour, eg by using stack.

**Comment by simonmichael** [comment]
(Incidentally, the same thing will eventually happen with all your more recent releases, since they too lack an upper bound on base. You're probably aware and maybe chose this trade off to reduce maintenance.)

**Comment by jtdaugherty** [comment]
> The fact is that you have some published some packages on Hackage with incorrect bounds

Yes, I agree.

> Though they're old versions none of us cares about, cabal can and will sometimes pick them for its install plan (as this real world example shows).. for its own inscrutable reasons.. 

Actually, the reason is usually a very good one and is not a matter of capricious or random cabal behavior. Once you add a brick bound that prevents it from using older ones, it will usually become clearer why it won't use newer ones, either.

> Putting a lower bound on brick could be a workaround but it's a kludge; it needlessly prevents someone building latest hledger with older brick versions

Except it's *not* a kludge when you *cannot build with older versions that have different APIs*. You can build *older* hledger versions with *older* bricks, but newer hledgers; it just isn't possible if you are using the newer brick API.

> Incidentally, the same thing will eventually happen with all your more recent releases, since they too lack an upper bound on base. You're probably aware and maybe chose this trade off to reduce maintenance.

Yeah, that's exactly right; it's tough to win either way. I go no upper bound because otherwise I get pull requests for every little drift of `base`, and that's super annoying to me. I agree that at some point upper bounds should be put in place, and I agree that I don't have a good practice of taking care of that.

**Comment by simonmichael** [comment]
> You can build older hledger versions with older bricks, but newer hledgers; it just isn't possible if you are using the newer brick API.

hledger tends to use CPP to adapt to old/new APIs, I assume it's doing this for brick too.

**Comment by simonmichael** [comment]
> I get pull requests for every little drift of base, and that's super annoying to me.

I relate to that!

I add upper bounds for base (major bounds - not persnickety minor ones) because it's pretty certain that a new GHC version will break my stuff. Likewise for other deps which tend to have troublesome-for-me API changes. Everything else, I omit the upper bounds.

**Comment by peti** [comment]
> > Putting a lower bound on brick could be a workaround but it's a kludge; it needlessly prevents someone building latest hledger with older brick versions
> 
> Except it's _not_ a kludge when you _cannot build with older versions that have different APIs_.

My understanding is that `hledger` builds just fine with older versions of `brick`, so putting a lower-bound restriction on `brick` in `hledger` does feel like a pretty bad idea to me.

**Comment by jtdaugherty** [comment]
I think it would be best if we conclude this conversation.

Thanks for your report, @simonmichael - in the future, I think it would be helpful for me if you could file a new ticket for any new issues you encounter (rather than commenting on old ones of the same variety).
